name: Continuous Integration

on: 
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  backend:
    name: backend-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - run: npm run build
      - uses: 
      - run: npm run test

  # frontend:
  #   name: frontend-ci
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./frontend
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 24
  #     - run: npm ci

